on:
  push:
    branches:
    - 'master'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      
      - name: Clone source code
        uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Setup params
        id: version-sha
        run: |
          IMAGE_VERSION=$(cat VERSION)
          SHORT_SHA1=$(git rev-parse --short HEAD)
          declare -a tags=(${IMAGE_VERSION} ${IMAGE_VERSION}:${SHORT_SHA1})
          for val in ${tags[@]}; do
            echo "Tagging and pushing $val"
          done
