on:
  push:
    branches:
    - 'master'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      
      - name: Clone source code
        uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Setup params
        id: version-sha
        run: |
          echo "##[set-output name=version;]$(cat VERSION)"
          echo "##[set-output name=sha_id;]$(git rev-parse --short HEAD)"

      - name: Docker login
        uses: azure/docker-login@v1
        with:
          login-server: quay.io
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        
      - name: Docker build, tag, and push
        run: |
          echo "Building image ${IMAGE_NAME}"
          cd ${IMAGE_VERSION}
          docker build -t ${IMAGE_NAME} .
          docker tag "${IMAGE_NAME}" "${IMAGE_NAME}:${IMAGE_VERSION}"
          echo "$Pushing {IMAGE_NAME}:${IMAGE_VERSION}"
          docker push "${IMAGE_NAME}:${IMAGE_VERSION}"
          docker tag "${IMAGE_NAME}" "${IMAGE_NAME}:${IMAGE_VERSION}-${SHORT_SHA1}"
          echo "Pushing ${IMAGE_NAME}:${IMAGE_VERSION}-${SHORT_SHA1}"
          docker push "${IMAGE_NAME}:${IMAGE_VERSION}-${SHORT_SHA1}"
        env:
          IMAGE_NAME: quay.io/ericwill/k8s-sidecar
          IMAGE_VERSION: ${{ steps.version-sha.outputs.version }}
          SHORT_SHA1: ${{ steps.version-sha.outputs.sha_id }}
